from app.models import Comment, db
from sqlalchemy.sql import text
from random import sample, randint

def comment_seeds(all_users, all_songs):
    comment1 = Comment(comment="Rocking out to this song feels like diving into a sea of raw energy and primal beats!", user_id=6, song_id=1,  song_time=16)
    comment2 = Comment(comment="Lost in the electrifying riff of this rock tune, time stands still as the music takes control!", user_id=2, song_id=2,  song_time=29)
    comment3 = Comment(comment="Turn up the volume and let this rock song transport you to a realm of pure musical euphoria!", user_id=5, song_id=3,  song_time=44)
    comment4 = Comment(comment="This rock masterpiece hits you like a sonic tidal wave, sweeping you up in its relentless rhythm and leaving you breathless!", user_id=1, song_id=4,  song_time=19)
    comment5 = Comment(comment="Strap in for a wild ride with this electrifying rock tune that's as fierce as a lightning bolt and as intense as a raging storm!", user_id=7, song_id=5,  song_time=47)
    comment6 = Comment(comment="This rock anthem is a sonic explosion of energy, shaking the foundations and stirring the soul with its electrifying intensity!", user_id=6, song_id=6,  song_time=3)
    comment7 = Comment(comment="The guitar riff in this rock tune is impressive, makes you want to turn up the volume and groove along.", user_id=3, song_id=7,  song_time=27)
    comment8 = Comment(comment="The rock song's rhythm is solid, and the vocals are strong, giving it a good energy.", user_id=5, song_id=8,  song_time=23)
    comment9 = Comment(comment="The rock song's rhythm is catchy, with a solid beat that keeps you moving.", user_id=10, song_id=9,  song_time=52)
    comment10 = Comment(comment="This rock song has a fantastic rhythm, it's impossible not to groove along.", user_id=9, song_id=10,  song_time=36)
    comment11 = Comment(comment="The pop song's beat is infectious, it's impossible not to move to.", user_id=3, song_id=11,  song_time=46)
    comment12 = Comment(comment="The pop song's rhythm is so catchy, it sticks in your head long after it's over.", user_id=7, song_id=12,  song_time=22)
    comment13 = Comment(comment="The rhythm of this pop song is irresistible, it's perfect for dancing.", user_id=9, song_id=13,  song_time=44)
    comment14 = Comment(comment="The pop song's rhythm is so catchy, it's hard not to bop along.", user_id=1, song_id=14,  song_time=38)
    comment15 = Comment(comment="The pop song's rhythm is infectious, it'll have you tapping your feet in no time.", user_id=4, song_id=15,  song_time=46)
    comment16 = Comment(comment="The pop song's rhythm is infectious, it'll have you moving from the first beat.", user_id=4, song_id=16,  song_time=1)
    comment17 = Comment(comment="The pop song's rhythm is groovy and upbeat, guaranteed to get you on your feet.", user_id=1, song_id=17,  song_time=34)
    comment18 = Comment(comment="In this pop song, the rhythm is infectious, urging you to move freely.", user_id=9, song_id=18,  song_time=26)
    comment19 = Comment(comment="This pop song's beat is so catchy, it's like a pulse you can't resist tapping along to!", user_id=10, song_id=19,  song_time=15)
    comment20 = Comment(comment="The pop song's rhythm is infectious, perfectly complementing the empowering lyrics.", user_id=9, song_id=20,  song_time=40)
    comment21 = Comment(comment="Basking in the warmth of this electronic track feels like a sunny day at the beach, with upbeat rhythms that lift your spirits.", user_id=7, song_id=21,  song_time=7)
    comment22 = Comment(comment="This electronic track radiates a sunny disposition with its bright synths and uplifting melodies, evoking feelings of joy and positivity.", user_id=1, song_id=22,  song_time=2)
    comment23 = Comment(comment="With its pulsating beats and vibrant melodies, this electronic track feels like a burst of sunshine on a cloudy day, infusing energy into every moment.", user_id=8, song_id=23,  song_time=18)
    comment24 = Comment(comment="This electronic track shines like a beacon of light on a sunny day, its infectious rhythms and uplifting melodies spreading warmth and positivity.", user_id=6, song_id=24,  song_time=60)
    comment25 = Comment(comment="Bathed in the sunny vibes of this electronic track, you'll feel your spirits lifted by its upbeat rhythms and radiant melodies.", user_id=9, song_id=25,  song_time=33)
    comment26 = Comment(comment="This electronic track gleams like sunlight on a clear day, with shimmering beats and uplifting melodies that evoke a sense of warmth and hope.", user_id=3, song_id=26,  song_time=9)
    comment27 = Comment(comment="The infectious beats of this electronic track make you want to jump up and dance, with energetic rhythms that pulse through your veins.", user_id=1, song_id=27,  song_time=54)
    comment28 = Comment(comment="The energetic beats of this electronic track inspire you to jump into the rhythm, moving with the pulsating energy that fills the air.", user_id=7, song_id=28,  song_time=2)
    comment29 = Comment(comment="This electronic track's infectious rhythm makes you want to jump up and lose yourself in the music, with its upbeat tempo and catchy hooks.", user_id=5, song_id=29,  song_time=20)
    comment30 = Comment(comment="The lively beats of this electronic track invite you to jump and dance, creating an atmosphere of pure energy and excitement.", user_id=6, song_id=30,  song_time=28)
    comment31 = Comment(comment="Its giving Mama Mia!", user_id=5, song_id=31,  song_time=21)
    comment32 = Comment(comment="Arctic Monkeys has inspired my entire music taste. I'm so thankful!", user_id=10, song_id=32,  song_time=32)
    comment33 = Comment(comment="The intro to this song is the best thing to add to a morning coffee!", user_id=6, song_id=33,  song_time=28)
    comment34 = Comment(comment="This whole album is just too good, but any album with this song on it just has to be great!", user_id=10, song_id=34,  song_time=23)
    comment35 = Comment(comment="The guitar is just TOO GOOD!", user_id=1, song_id=35,  song_time=54)
    comment36 = Comment(comment="This intro just gets me moving, how do they do it?!!", user_id=8, song_id=36,  song_time=54)
    comment37 = Comment(comment="I feel like I've heard this opening riff before...", user_id=5, song_id=37,  song_time=12)
    comment38 = Comment(comment="This song is my forever shower song! Just a perfect vibe!", user_id=3, song_id=38,  song_time=38)
    comment39 = Comment(comment="Taylor robbed you!!!", user_id=8, song_id=39,  song_time=59)
    comment40 = Comment(comment="What a throwback!", user_id=3, song_id=40,  song_time=29)
    comment41 = Comment(comment="What a great track to work to!", user_id=1, song_id=41,  song_time=15)
    comment42 = Comment(comment="Chelle Ives does it again!", user_id=10, song_id=42,  song_time=38)
    comment43 = Comment(comment="TEACH ME YOUR WAYS DYE O!", user_id=2, song_id=43,  song_time=11)
    comment44 = Comment(comment="Epoch has got to be their best album, well done!", user_id=4, song_id=44,  song_time=53)
    comment45 = Comment(comment="ELFL, how do you do it?", user_id=5, song_id=45,  song_time=7)
    comment46 = Comment(comment="Who knew Hauntology would have my favorite song?", user_id=1, song_id=46,  song_time=18)
    comment47 = Comment(comment="Electronic music has the best subcategories.", user_id=5, song_id=47,  song_time=23)
    comment48 = Comment(comment="Ok, who told you that you could make such a good song? It makes the rest of us look bad...", user_id=9, song_id=48,  song_time=32)
    comment49 = Comment(comment="Top Hauntology track BY FAR!", user_id=3, song_id=49,  song_time=53)
    comment50 = Comment(comment="Lemme get a verse, insta hit!", user_id=4, song_id=50,  song_time=54)
    comment51 = Comment(comment="One of his best.", user_id=10, song_id=51,  song_time=5)
    comment52 = Comment(comment="This was at my first Opera, bringing back great memories!", user_id=6, song_id=52,  song_time=43)
    comment53 = Comment(comment="Just lovely!", user_id=8, song_id=53,  song_time=42)
    comment54 = Comment(comment="A waltz on violin? Such a grand idea!", user_id=5, song_id=54,  song_time=4)
    comment55 = Comment(comment="Such a lovely voice. ", user_id=3, song_id=55,  song_time=45)
    comment56 = Comment(comment="Can't stop listening!", user_id=10, song_id=56,  song_time=54)
    comment57 = Comment(comment="What a great piece!", user_id=3, song_id=57,  song_time=53)
    comment58 = Comment(comment="Can't stop listening!", user_id=5, song_id=58,  song_time=57)
    comment59 = Comment(comment="What an iconic piece!", user_id=9, song_id=59,  song_time=36)
    comment60 = Comment(comment="Great piece!", user_id=7, song_id=60,  song_time=52)
    comment61 = Comment(comment="'Sunflower' has this chill and feel-good vibe that's perfect for any mood.", user_id=1, song_id=61,  song_time=12)
    comment62 = Comment(comment="'Love the Way You Lie' is a powerful collaboration – Eminem and Rihanna's chemistry is unmatched.", user_id=3, song_id=62,  song_time=17)
    comment63 = Comment(comment="Eminem's 'Lose Yourself' is the ultimate motivational anthem – it's like a pump-up speech in a song.", user_id=5, song_id=63,  song_time=14)
    comment64 = Comment(comment="'See You Again' is an emotional masterpiece, a tribute that hits right in the heart.", user_id=3, song_id=64,  song_time=5)
    comment65 = Comment(comment="'Empire State of Mind' is an anthem that captures the essence of New York City – love the energy!", user_id=7, song_id=65,  song_time=55)
    comment66 = Comment(comment="Drake's 'One Dance' is a vibe – it's impossible not to move when this song comes on.", user_id=5, song_id=66,  song_time=48)
    comment67 = Comment(comment="The combination of B.o.B and Hayley Williams' voices in 'Airplanes' creates a perfect blend of rap and emotion.", user_id=9, song_id=67,  song_time=2)
    comment68 = Comment(comment="This song is a vibe! Nicki Minaj's 'Super Bass' is like an energy boost – perfect for any mood.", user_id=7, song_id=68,  song_time=29)
    comment69 = Comment(comment="The chorus of 'Believer' hits hard, and the way the lyrics express overcoming struggles resonates with me on a personal level.", user_id=3, song_id=69,  song_time=27)
    comment70 = Comment(comment="这首 '差不多先生' 的rap充满了创新和独特的音乐元素，展示了艺术家独特的风格和才华。", user_id=7, song_id=70,  song_time=17)
    comment71 = Comment(comment="'Riptide' always puts me in a good mood – such a breezy and uplifting tune!", user_id=2, song_id=71,  song_time=17)
    comment72 = Comment(comment="The lyrics of 'Counting Stars' are so relatable, and the beat is just infectious.", user_id=8, song_id=72,  song_time=13)
    comment73 = Comment(comment="'Put It All on Me' by Ed Sheeran is a sweet and heartfelt love song – pure romance!", user_id=1, song_id=73,  song_time=2)
    comment74 = Comment(comment="'Three Little Birds' by Bob Marley is my instant stress-reliever – it's like a musical hug.", user_id=5, song_id=74,  song_time=60)
    comment75 = Comment(comment="'I'm Yours' is a song that brings a smile to my face every time I hear it.", user_id=7, song_id=75,  song_time=17)
    comment76 = Comment(comment="'Budapest' by George Ezra is a travel anthem – makes me want to explore the world.", user_id=10, song_id=76,  song_time=21)
    comment77 = Comment(comment="Jack Johnson's 'Banana Pancakes' is like a warm hug on a lazy Sunday morning.", user_id=10, song_id=77,  song_time=29)
    comment78 = Comment(comment="'Hey Soul Sister' by Train is a song that brings back nostalgic memories – timeless.", user_id=4, song_id=78,  song_time=39)
    comment79 = Comment(comment="'The Lazy Song' by Bruno Mars is my anthem for those lazy, carefree days.", user_id=6, song_id=79,  song_time=5)
    comment80 = Comment(comment="'Fireflies' by Owl City is a whimsical journey through a dreamy, musical landscape.", user_id=3, song_id=80,  song_time=30)
    comment81 = Comment(comment="2024 whos still blasting real music", user_id=9, song_id=81,  song_time=60)
    comment82 = Comment(comment="2024 and still listening to this beautiful song", user_id=4, song_id=82,  song_time=52)
    comment83 = Comment(comment="It's 2024 and I'm still listening to boot scootin boogie", user_id=2, song_id=83,  song_time=29)
    comment84 = Comment(comment="I don’t usually lose much peace over celebrity deaths, but this one hit me hard.  He was my favorite modern country artist and a true Patriot.  His music spoke to me where most does not.", user_id=1, song_id=84,  song_time=52)
    comment85 = Comment(comment="This was the last era of country, less country than George Strait or Garth but more country than Dan and Shay.", user_id=10, song_id=85,  song_time=44)
    comment86 = Comment(comment="I bump this song all the time in my car...LOUDLY!", user_id=1, song_id=86,  song_time=50)
    comment87 = Comment(comment="What a carefree happy song.", user_id=7, song_id=87,  song_time=27)
    comment88 = Comment(comment="Another great song", user_id=2, song_id=88,  song_time=8)
    comment89 = Comment(comment="What if the tractor was red", user_id=5, song_id=89,  song_time=19)
    comment90 = Comment(comment="We need to bring this era of country back, it was the best", user_id=8, song_id=90,  song_time=40)
    comment91 = Comment(comment="I had no idea Sam was a metal head. This is such an awesome song", user_id=3, song_id=91,  song_time=17)
    comment92 = Comment(comment="This is so epic and theatrical stoked for the next drop. You really know how to take us on a journey with your music.", user_id=9, song_id=92,  song_time=6)
    comment93 = Comment(comment="this is so original I can't really fit it into a genre. It sounds awesome man. the vocals are killer too", user_id=6, song_id=93,  song_time=56)
    comment94 = Comment(comment="These new tracks are insanely good.", user_id=2, song_id=94,  song_time=45)
    comment95 = Comment(comment="Dude. this is freaking insanely good.", user_id=6, song_id=95,  song_time=46)
    comment96 = Comment(comment="This slaps. I love it.", user_id=5, song_id=96,  song_time=22)
    comment97 = Comment(comment="Literally so underrated", user_id=6, song_id=97,  song_time=17)
    comment98 = Comment(comment="Found my crusade music.", user_id=4, song_id=98,  song_time=50)
    comment99 = Comment(comment="Love this song!", user_id=7, song_id=99,  song_time=32)
    comment100 = Comment(comment="What a banger of a song", user_id=9, song_id=100,  song_time=59)
    comment101 = Comment(comment="This rock anthem cranks up the volume and ignites an unstoppable fire within!", user_id=1, song_id=1,  song_time=20)
    comment102 = Comment(comment="From the moment the first chord strikes, this rock anthem takes you on a wild ride through a sonic landscape of pure adrenaline!", user_id=5, song_id=2,  song_time=56)
    comment103 = Comment(comment="Crunchy guitars, pounding drums, and gritty vocals make this rock song an instant classic!", user_id=6, song_id=3,  song_time=45)
    comment104 = Comment(comment="With each riff and beat, this rock anthem builds an unstoppable momentum that unleashes a surge of pure adrenaline!", user_id=10, song_id=4,  song_time=50)
    comment105 = Comment(comment="With its soaring vocals and thunderous guitar solos, this rock anthem is a sonic rollercoaster that leaves you exhilarated and craving more!", user_id=4, song_id=5,  song_time=45)
    comment106 = Comment(comment="With its driving rhythm and blistering guitar solos, this rock song is a roaring inferno that ignites the spirit and fuels the rebellion!", user_id=4, song_id=6,  song_time=33)
    comment107 = Comment(comment="Listening to this track, you find yourself tapping your foot to the beat, it's really catchy.", user_id=6, song_id=7,  song_time=27)
    comment108 = Comment(comment="This track is catchy, with a beat that makes you want to nod along as you listen.", user_id=8, song_id=8,  song_time=38)
    comment109 = Comment(comment="This track has a great vibe, making you tap your foot along with the music.", user_id=2, song_id=9,  song_time=24)
    comment110 = Comment(comment="Listening to this track, you can feel the energy pulsating through every note.", user_id=9, song_id=10,  song_time=5)
    comment111 = Comment(comment="Listening to this track, you can't help but get caught up in its catchy melody.", user_id=1, song_id=11,  song_time=36)
    comment112 = Comment(comment="This track has a great melody that you can't help but hum along to.", user_id=10, song_id=12,  song_time=28)
    comment113 = Comment(comment="Listening to this track, you'll find yourself humming the melody for days.", user_id=10, song_id=13,  song_time=28)
    comment114 = Comment(comment="This track's melody is infectious, you'll find yourself humming it all day.", user_id=2, song_id=14,  song_time=6)
    comment115 = Comment(comment="This track's melody is so catchy, you'll find yourself singing along unconsciously.", user_id=5, song_id=15,  song_time=46)
    comment116 = Comment(comment="This track's instrumentation is lively and vibrant, adding layers of depth to the music.", user_id=4, song_id=16,  song_time=24)
    comment117 = Comment(comment="This track's instrumental arrangement is dynamic, with layers of sound that keep you hooked.", user_id=8, song_id=17,  song_time=34)
    comment118 = Comment(comment="The instrumentation in this track is rich and vibrant, painting a vivid musical landscape.", user_id=6, song_id=18,  song_time=15)
    comment119 = Comment(comment="Listening to this track, you're swept away by its dreamy melody and uplifting vibes.", user_id=4, song_id=19,  song_time=22)
    comment120 = Comment(comment="This track's melody, sung with captivating vocals, tells a story of strength and resilience.", user_id=4, song_id=20,  song_time=22)
    comment121 = Comment(comment="Despite its drainy undertones, this electronic song possesses a hypnotic energy that draws you into its dark, pulsating depths.", user_id=1, song_id=21,  song_time=20)
    comment122 = Comment(comment="Immerse yourself in the drainy atmosphere of this electronic song, where brooding basslines and haunting vocals create an atmosphere of introspection.", user_id=9, song_id=22,  song_time=59)
    comment123 = Comment(comment="Dive into the drainy depths of this electronic song, where haunting synths and echoing vocals create an atmosphere of eerie beauty.", user_id=3, song_id=23,  song_time=43)
    comment124 = Comment(comment="Exploring the drainy depths of this electronic song, you'll find yourself submerged in a sea of brooding basslines and melancholic melodies.", user_id=2, song_id=24,  song_time=8)
    comment125 = Comment(comment="Descending into the drainy soundscape of this electronic song, you'll be enveloped by its haunting echoes and hypnotic beats.", user_id=1, song_id=25,  song_time=22)
    comment126 = Comment(comment="Submerged in the drainy depths of this electronic song, you'll find yourself enveloped in a dark, immersive atmosphere punctuated by haunting vocals and deep basslines.", user_id=2, song_id=26,  song_time=31)
    comment127 = Comment(comment="Cruising down the highway with the windows down, this electronic song provides the perfect soundtrack for a late-night drive, with its driving basslines and pulsating beats.", user_id=8, song_id=27,  song_time=16)
    comment128 = Comment(comment="As you hit the road, the driving basslines of this electronic song fuel your adrenaline, creating the perfect soundtrack for a thrilling drive under the open sky.", user_id=3, song_id=28,  song_time=53)
    comment129 = Comment(comment="Cruising down the open road with this electronic song blasting through the speakers, its driving beat adds an extra layer of excitement to your drive.", user_id=5, song_id=29,  song_time=60)
    comment130 = Comment(comment="Driving through the city streets with this electronic song as your soundtrack, its driving bass and dynamic rhythms fuel your sense of adventure.", user_id=7, song_id=30,  song_time=56)
    comment131 = Comment(comment="This song is my go to for workouts!!", user_id=5, song_id=31,  song_time=43)
    comment132 = Comment(comment="Would love to be FIRESIDE with the Arctic Monkeys!", user_id=2, song_id=32,  song_time=26)
    comment133 = Comment(comment="No mister Arctic Monkeys, I wanna be YOURS!!", user_id=8, song_id=33,  song_time=23)
    comment134 = Comment(comment="Best song on the album, hands down!", user_id=7, song_id=34,  song_time=56)
    comment135 = Comment(comment="How does Arctic Monkeys release an album just FILLED WITH SO MANY GREAT SONGS??!!", user_id=7, song_id=35,  song_time=10)
    comment136 = Comment(comment="Dance, Dance? How could I not??", user_id=6, song_id=36,  song_time=1)
    comment137 = Comment(comment="The Foo Fighters just don't miss!", user_id=4, song_id=37,  song_time=49)
    comment138 = Comment(comment="Hoobastank don't lie, only a perfect person could make the perfect song!", user_id=3, song_id=38,  song_time=54)
    comment139 = Comment(comment="How is this NOT an grammy winning song?!?!?!!!", user_id=4, song_id=39,  song_time=56)
    comment140 = Comment(comment="This song was on repeat for a whole summer!", user_id=5, song_id=40,  song_time=50)
    comment141 = Comment(comment="Who doesn't love this song? I'd have something to say to them...", user_id=10, song_id=41,  song_time=14)
    comment142 = Comment(comment="Love the beats!", user_id=8, song_id=42,  song_time=9)
    comment143 = Comment(comment="Throwing this track on repeat to get all my work done NEVER fails!", user_id=4, song_id=43,  song_time=38)
    comment144 = Comment(comment="This is the song I ignore my boss to!", user_id=9, song_id=44,  song_time=56)
    comment145 = Comment(comment="These beats are everything!", user_id=7, song_id=45,  song_time=28)
    comment146 = Comment(comment="Love the beats!", user_id=9, song_id=46,  song_time=25)
    comment147 = Comment(comment="This track has me moving my feet to the beat, great job!", user_id=10, song_id=47,  song_time=23)
    comment148 = Comment(comment="If you like this song, you'll love mine, Check it out!", user_id=3, song_id=48,  song_time=17)
    comment149 = Comment(comment="The saxaphone was a perfect choice, loving the whole track!", user_id=8, song_id=49,  song_time=34)
    comment150 = Comment(comment="Check out my track.", user_id=7, song_id=50,  song_time=10)
    comment151 = Comment(comment="Cant believe he never published this, its amazing!", user_id=2, song_id=51,  song_time=42)
    comment152 = Comment(comment="Getting a ticket to see this performed live!", user_id=7, song_id=52,  song_time=55)
    comment153 = Comment(comment="Great work, studying never felt so easy.", user_id=4, song_id=53,  song_time=9)
    comment154 = Comment(comment="I didn't like violin until this piece!", user_id=5, song_id=54,  song_time=10)
    comment155 = Comment(comment="How does she do it?", user_id=3, song_id=55,  song_time=59)
    comment156 = Comment(comment="Just found out I enjoy classical music, what a great piece to learn it to!", user_id=2, song_id=56,  song_time=28)
    comment157 = Comment(comment="Feels like I'm watching all over again!", user_id=7, song_id=57,  song_time=56)
    comment158 = Comment(comment="Great work, studying never felt so easy.", user_id=8, song_id=58,  song_time=25)
    comment159 = Comment(comment="Tell me again why I can't listen to this on repeat?", user_id=5, song_id=59,  song_time=57)
    comment160 = Comment(comment="This is a treat!", user_id=8, song_id=60,  song_time=39)
    comment161 = Comment(comment="The melody and lyrics of 'Sunflower' create such a laid-back atmosphere – a true vibe.", user_id=4, song_id=61,  song_time=36)
    comment162 = Comment(comment="The raw emotion in both Eminem's rap and Rihanna's vocals makes 'Love the Way You Lie' unforgettable.", user_id=3, song_id=62,  song_time=21)
    comment163 = Comment(comment="'Lose Yourself' is a classic – the intensity in Eminem's delivery still gives me chills.", user_id=6, song_id=63,  song_time=18)
    comment164 = Comment(comment="The lyrics and melody of 'See You Again' are so powerful; it's a song that stays with you.", user_id=6, song_id=64,  song_time=27)
    comment165 = Comment(comment="Alicia Keys' vocals combined with Jay-Z's rap in 'Empire State of Mind' create a perfect harmony.", user_id=3, song_id=65,  song_time=42)
    comment166 = Comment(comment="The chill and laid-back feel of 'One Dance' makes it a go-to track for a relaxing time.", user_id=5, song_id=66,  song_time=58)
    comment167 = Comment(comment="'Airplanes' is that timeless song that never gets old; the lyrics are deep and relatable.", user_id=6, song_id=67,  song_time=26)
    comment168 = Comment(comment="Whenever 'Super Bass' plays, it's an instant mood-lifter – Nicki Minaj's charisma shines through!", user_id=4, song_id=68,  song_time=57)
    comment169 = Comment(comment="Imagine Dragons nailed it with 'Believer' – the combination of the catchy melody and meaningful lyrics makes it a go-to song when I need a boost.", user_id=2, song_id=69,  song_time=33)
    comment170 = Comment(comment="这首歌的节奏和歌词充满力量，展示了艺术家对于音乐表达的深刻理解，让人回味无穷。", user_id=8, song_id=70,  song_time=17)
    comment171 = Comment(comment="The ukulele in 'Riptide' gives it a unique sound that makes me want to sing along.", user_id=8, song_id=71,  song_time=12)
    comment172 = Comment(comment="'Counting Stars' is that anthem for dreaming big – it resonates with my aspirations.", user_id=6, song_id=72,  song_time=12)
    comment173 = Comment(comment="Ed Sheeran's storytelling in 'Put It All on Me' makes it so easy to connect with.", user_id=6, song_id=73,  song_time=42)
    comment174 = Comment(comment="Bob Marley's 'Three Little Birds' always lifts my spirits – a timeless feel-good classic.", user_id=5, song_id=74,  song_time=11)
    comment175 = Comment(comment="Jason Mraz's 'I'm Yours' has this easygoing vibe that's perfect for any occasion.", user_id=3, song_id=75,  song_time=47)
    comment176 = Comment(comment="The folk-pop vibe of 'Budapest' is so refreshing and easy to listen to.", user_id=7, song_id=76,  song_time=37)
    comment177 = Comment(comment="'Banana Pancakes' creates a cozy atmosphere – perfect for a chill day at home.", user_id=6, song_id=77,  song_time=10)
    comment178 = Comment(comment="Train's 'Hey Soul Sister' has this upbeat energy that always makes me want to dance.", user_id=7, song_id=78,  song_time=42)
    comment179 = Comment(comment="Bruno Mars captures the essence of relaxation in 'The Lazy Song' – love it!", user_id=8, song_id=79,  song_time=13)
    comment180 = Comment(comment="The nostalgic feel of 'Fireflies' always takes me back to a simpler time.", user_id=2, song_id=80,  song_time=31)
    comment181 = Comment(comment="Modern songs will never be better than old school songs NEVER! Old is gold", user_id=8, song_id=81,  song_time=60)
    comment182 = Comment(comment="2024 and this is still a great timeless song.", user_id=1, song_id=82,  song_time=15)
    comment183 = Comment(comment="When country was county and not hip hop", user_id=9, song_id=83,  song_time=18)
    comment184 = Comment(comment="RIP handsome. Beautiful soul inside and out", user_id=9, song_id=84,  song_time=4)
    comment185 = Comment(comment="The real taste of Country Music", user_id=2, song_id=85,  song_time=54)
    comment186 = Comment(comment="Bro, that thang hit HARRRRRD at the beginning!!!!!", user_id=4, song_id=86,  song_time=17)
    comment187 = Comment(comment="Felt like I heard this song when I was way younger, still love it", user_id=3, song_id=87,  song_time=47)
    comment188 = Comment(comment="It Is a true gem of a song!", user_id=1, song_id=88,  song_time=44)
    comment189 = Comment(comment="Ngl this song gets better the more you age.", user_id=8, song_id=89,  song_time=22)
    comment190 = Comment(comment="From her cowboy boots to her down home roots", user_id=5, song_id=90,  song_time=24)
    comment191 = Comment(comment="The perfect blend of overlapping melodies with juicy riffs is what really makes it stand out I feel.", user_id=10, song_id=91,  song_time=9)
    comment192 = Comment(comment="This is my fav of the new ones so far! Still freaking me out with those single coils", user_id=6, song_id=92,  song_time=51)
    comment193 = Comment(comment="Such an absolute slapper as always Sam!!", user_id=8, song_id=93,  song_time=9)
    comment194 = Comment(comment="Yes dude. Hell yes.", user_id=8, song_id=94,  song_time=1)
    comment195 = Comment(comment="Bruh! Outstanding work Sam", user_id=1, song_id=95,  song_time=12)
    comment196 = Comment(comment="Every one of these has been a banger so far.", user_id=6, song_id=96,  song_time=57)
    comment197 = Comment(comment="this sounds incredible", user_id=7, song_id=97,  song_time=2)
    comment198 = Comment(comment="Even 10 years later this song is still a masterpiece.", user_id=6, song_id=98,  song_time=58)
    comment199 = Comment(comment="Guitar solo is awesome!", user_id=4, song_id=99,  song_time=31)
    comment200 = Comment(comment="Can't stop banging my head!", user_id=10, song_id=100,  song_time=60)
    comment201 = Comment(comment="This song is like a thunderous avalanche of guitars and drums, crashing through the speakers with unstoppable force!", user_id=3, song_id=1,  song_time=33)
    comment202 = Comment(comment="This rock song is a sonic blast that shakes the soul and leaves you craving more!", user_id=8, song_id=2,  song_time=41)
    comment203 = Comment(comment="Feel the pulse of this rock anthem pulsating through your veins, igniting a fire within that refuses to be extinguished!", user_id=9, song_id=3,  song_time=28)
    comment204 = Comment(comment="From the gritty vocals to the thunderous drums, this rock song is a powerhouse of raw emotion that demands to be heard!", user_id=10, song_id=4,  song_time=51)
    comment205 = Comment(comment="From the first chord to the final crescendo, this rock song is a high-octane thrill ride that sets your heart racing and your soul on fire!", user_id=9, song_id=5,  song_time=52)
    comment206 = Comment(comment="From the pounding drums to the wailing vocals, this rock tune is a fierce and fiery declaration of independence that demands to be heard!", user_id=3, song_id=6,  song_time=57)
    comment207 = Comment(comment="The guitar riff in this rock tune is impressive, makes you want to turn up the volume and groove along.", user_id=2, song_id=7,  song_time=59)
    comment208 = Comment(comment="The guitar riff in this rock tune stands out, making you want to turn it up and really get into it.", user_id=2, song_id=8,  song_time=15)
    comment209 = Comment(comment="The guitar riff in this rock tune is standout, it really grabs your attention.", user_id=6, song_id=9,  song_time=60)
    comment210 = Comment(comment="The guitar riff in this rock tune is unforgettable, it leaves a lasting impression.", user_id=8, song_id=10,  song_time=9)
    comment211 = Comment(comment="The instrumental arrangement in this pop tune is captivating, it keeps you hooked from start to finish.", user_id=2, song_id=11,  song_time=50)
    comment212 = Comment(comment="The instrumental arrangement in this pop tune is really well-crafted, it's a joy to listen to.", user_id=7, song_id=12,  song_time=14)
    comment213 = Comment(comment="The instrumental arrangement in this pop tune is so catchy, it's bound to get stuck in your head.", user_id=7, song_id=13,  song_time=2)
    comment214 = Comment(comment="The instrumental arrangement in this pop tune is really well done, it's a pleasure to listen to.", user_id=6, song_id=14,  song_time=40)
    comment215 = Comment(comment="The instrumental arrangement in this pop tune is expertly crafted, it's pure ear candy.", user_id=9, song_id=15,  song_time=41)
    comment216 = Comment(comment="The instrumental arrangement in this pop tune is diverse and engaging, keeping your ears entertained throughout.", user_id=9, song_id=16,  song_time=7)
    comment217 = Comment(comment="The music in this pop tune is lively and energetic, making it impossible to sit still.", user_id=7, song_id=17,  song_time=14)
    comment218 = Comment(comment="The music in this piece is lively and spirited, echoing a sense of liberation and joy.", user_id=4, song_id=18,  song_time=52)
    comment219 = Comment(comment="The instrumentation in this pop tune is like a colorful tapestry, weaving together different sounds into a harmonious blend.", user_id=9, song_id=19,  song_time=19)
    comment220 = Comment(comment="The instrumentation in this pop tune creates a vibrant backdrop for the empowering female vocals.", user_id=1, song_id=20,  song_time=5)
    comment221 = Comment(comment="The electronic beats in this track cast a shadow over a cloudy landscape, blending melancholy melodies with futuristic soundscape.", user_id=10, song_id=21,  song_time=3)
    comment222 = Comment(comment="Floating amidst a cloudy haze of ethereal sounds, this electronic track transports you to a dreamlike realm where time seems to stand still.", user_id=6, song_id=22,  song_time=44)
    comment223 = Comment(comment="Lost in a cloudy haze of ethereal soundscapes, this electronic track takes you on a journey through a surreal landscape of shimmering synths and distant echoes.", user_id=8, song_id=23,  song_time=51)
    comment224 = Comment(comment="In the cloudy ambiance of this electronic track, swirling synths and distant whispers create an otherworldly atmosphere that captivates the senses.", user_id=3, song_id=24,  song_time=57)
    comment225 = Comment(comment="Navigating through the cloudy layers of this electronic track, you'll discover a mesmerizing blend of ethereal synths and pulsating rhythms that transport you to another realm.", user_id=3, song_id=25,  song_time=17)
    comment226 = Comment(comment="Through the cloudy haze of this electronic track, ethereal melodies and dreamlike synths weave together to create a mesmerizing sonic journey that transports you to distant realms.", user_id=3, song_id=26,  song_time=8)
    comment227 = Comment(comment="With its soaring synths and uplifting melodies, this electronic track makes you feel like you're soaring through the sky, embracing the freedom to fly wherever the music takes you.", user_id=5, song_id=27,  song_time=45)
    comment228 = Comment(comment="Transporting you to new heights, the ethereal soundscape of this electronic track makes you feel like you're flying through a dream, carried by the uplifting melodies and atmospheric beats.", user_id=4, song_id=28,  song_time=11)
    comment229 = Comment(comment="With its soaring melodies and pulsating rhythm, this electronic track feels like a journey through the clouds, lifting you up and allowing you to fly to new heights.", user_id=10, song_id=29,  song_time=14)
    comment230 = Comment(comment="As the electronic melodies fill the air, you feel as though you're flying through a dreamscape, carried by the euphoric energy of the music.", user_id=9, song_id=30,  song_time=12)
    comment231 = Comment(comment="Everything now! Everything now! Everything now!", user_id=6, song_id=31,  song_time=3)
    comment232 = Comment(comment="Best song on this album!!!", user_id=7, song_id=32,  song_time=36)
    comment233 = Comment(comment="How do they make such GREAT songs so CONSISTENTLY?!?!?!", user_id=9, song_id=33,  song_time=20)
    comment234 = Comment(comment="Satisfaction feels like a distant memory... Such a lie when I listen to this song!", user_id=2, song_id=34,  song_time=34)
    comment235 = Comment(comment="Left you multiple missed calls and to my message you reply? Sounds like we have the same friends...", user_id=10, song_id=35,  song_time=57)
    comment236 = Comment(comment="Misery of me? Not when this song comes on!", user_id=9, song_id=36,  song_time=38)
    comment237 = Comment(comment="If you say you don't like this song, then YOU'RE THE PRETENDER!!", user_id=4, song_id=37,  song_time=42)
    comment238 = Comment(comment="So beautiful, AND THE REASON IS YOUUUUUUUU!!!!", user_id=7, song_id=38,  song_time=3)
    comment239 = Comment(comment="Boycot the Grammy's, they have bad taste!", user_id=2, song_id=39,  song_time=50)
    comment240 = Comment(comment="Summertime sadness? That only happens when I don't hear this song in the summer", user_id=9, song_id=40,  song_time=15)
    comment241 = Comment(comment="The beats just get me GROOVING!", user_id=5, song_id=41,  song_time=33)
    comment242 = Comment(comment="Everyone agrees this track is great right? RIGHT??", user_id=7, song_id=42,  song_time=22)
    comment243 = Comment(comment="Tell me again why I should listen to other music?", user_id=9, song_id=43,  song_time=22)
    comment244 = Comment(comment="When is the concert, this would be great to hear live!", user_id=5, song_id=44,  song_time=31)
    comment245 = Comment(comment="I need this playing everywhere I go!", user_id=2, song_id=45,  song_time=33)
    comment246 = Comment(comment="The cover image is just so cool!", user_id=1, song_id=46,  song_time=45)
    comment247 = Comment(comment="No one should have all this talent... it's just unfair to the rest of us!", user_id=3, song_id=47,  song_time=6)
    comment248 = Comment(comment="This is your best work!!", user_id=8, song_id=48,  song_time=48)
    comment249 = Comment(comment="Mama Zula, how do you do it? ", user_id=2, song_id=49,  song_time=19)
    comment250 = Comment(comment="Great beats, when you gonna get me in the studio?", user_id=8, song_id=50,  song_time=43)
    comment251 = Comment(comment="I don't know who Elise is, but she must have been very special.", user_id=7, song_id=51,  song_time=51)
    comment252 = Comment(comment="Great piece!", user_id=8, song_id=52,  song_time=41)
    comment253 = Comment(comment="This is why I passed my biology exam, so thankful!", user_id=5, song_id=53,  song_time=50)
    comment254 = Comment(comment="My wife just LOVES dancing to this!", user_id=2, song_id=54,  song_time=16)
    comment255 = Comment(comment="This is a great piece, just lovely.", user_id=8, song_id=55,  song_time=48)
    comment256 = Comment(comment="This is a treat!", user_id=4, song_id=56,  song_time=28)
    comment257 = Comment(comment="Absolutely lovely.", user_id=10, song_id=57,  song_time=24)
    comment258 = Comment(comment="Great piece!", user_id=6, song_id=58,  song_time=5)
    comment259 = Comment(comment="Just lovely!", user_id=8, song_id=59,  song_time=55)
    comment260 = Comment(comment="Can't stop listening!", user_id=2, song_id=60,  song_time=42)
    comment261 = Comment(comment="'Sunflower' is a song that brings sunshine to my playlist – it's impossible not to enjoy.", user_id=7, song_id=61,  song_time=29)
    comment262 = Comment(comment="This song captures the complexity of relationships and resonates with so many emotions.", user_id=3, song_id=62,  song_time=2)
    comment263 = Comment(comment="This song is a reminder to seize the moment and give it everything you've got – timeless inspiration.", user_id=5, song_id=63,  song_time=24)
    comment264 = Comment(comment="Whenever I listen to this song, it brings back memories and emotions – a beautiful tribute.", user_id=7, song_id=64,  song_time=53)
    comment265 = Comment(comment="This song makes me dream big and feel the excitement of being in the 'concrete jungle where dreams are made of.'", user_id=6, song_id=65,  song_time=30)
    comment266 = Comment(comment="Whenever I hear 'One Dance,' it takes me back to some great memories – such a nostalgic tune.", user_id=7, song_id=66,  song_time=31)
    comment267 = Comment(comment="Hayley's chorus in 'Airplanes' hits differently – it adds such a beautiful and emotional layer to the rap verses.", user_id=1, song_id=67,  song_time=3)
    comment268 = Comment(comment="Nicki Minaj killed it with 'Super Bass' – a catchy anthem that never gets old.", user_id=1, song_id=68,  song_time=46)
    comment271 = Comment(comment="Vance Joy's 'Riptide' is that song I never get tired of – it's just so catchy and feel-good.", user_id=10, song_id=71,  song_time=45)
    comment272 = Comment(comment="OneRepublic nailed it with 'Counting Stars' – it's a song that stays with you.", user_id=7, song_id=72,  song_time=22)
    comment273 = Comment(comment="'Put It All on Me' is the kind of song that makes me believe in love – beautiful lyrics.", user_id=8, song_id=73,  song_time=49)
    comment275 = Comment(comment="'I'm Yours' is that song I can't help but sing along to – such a happy melody.", user_id=4, song_id=75,  song_time=40)
    comment276 = Comment(comment="'Budapest' has a charming melody – George Ezra's voice just draws you in.", user_id=6, song_id=76,  song_time=60)
    comment277 = Comment(comment=	"The simplicity of 'Banana Pancakes' by Jack Johnson is its charm – just pure relaxation.", user_id=1, song_id=77,  song_time=19)
    comment278 = Comment(comment="Whenever I hear 'Hey Soul Sister,' it's an instant mood lifter – such a fun tune.", user_id=6, song_id=78,  song_time=48)
    comment279 = Comment(comment="Whenever I need a break, 'The Lazy Song' is my go-to reminder to just chill.", user_id=10, song_id=79,  song_time=38)
    comment280 = Comment(comment="'Fireflies' is that magical song that sparks the imagination – love the dreamy vibe.", user_id=9, song_id=80,  song_time=48)

    all_comments = [comment1, comment2, comment3, comment4, comment5, comment6, comment7, comment8, comment9, comment10, comment11, comment12, comment13, comment14, comment15, comment16, comment17, comment18, comment19, comment20, comment21, comment22, comment23, comment24, comment25, comment26, comment27, comment28, comment29, comment30, comment31, comment32, comment33, comment34, comment35, comment36, comment37, comment38, comment39, comment40, comment41, comment42, comment43, comment44, comment45, comment46, comment47, comment48, comment49, comment50, comment51, comment52, comment53, comment54, comment55, comment56, comment57, comment58, comment59, comment60, comment61, comment62, comment63, comment64, comment65, comment66, comment67, comment68, comment69, comment70, comment71, comment72, comment73, comment74, comment75, comment76, comment77, comment78, comment79, comment80, comment81, comment82, comment83, comment84, comment85, comment86, comment87, comment88, comment89, comment90, comment91, comment92, comment93, comment94, comment95, comment96, comment97, comment98, comment99, comment100, comment101, comment102, comment103, comment104, comment105, comment106, comment107, comment108, comment109, comment110, comment111, comment112, comment113, comment114, comment115, comment116, comment117, comment118, comment119, comment120, comment121, comment122, comment123, comment124, comment125, comment126, comment127, comment128, comment129, comment130, comment131, comment132, comment133, comment134, comment135, comment136, comment137, comment138, comment139, comment140, comment141, comment142, comment143, comment144, comment145, comment146, comment147, comment148, comment149, comment150, comment151, comment152, comment153, comment154, comment155, comment156, comment157, comment158, comment159, comment160, comment161, comment162, comment163, comment164, comment165, comment166, comment167, comment168, comment169, comment170, comment171, comment172, comment173, comment174, comment175, comment176, comment177, comment178, comment179, comment180, comment181, comment182, comment183, comment184, comment185, comment186, comment187, comment188, comment189, comment190, comment191, comment192, comment193, comment194, comment195, comment196, comment197, comment198, comment199, comment200, comment201, comment202, comment203, comment204, comment205, comment206, comment207, comment208, comment209, comment210, comment211, comment212, comment213, comment214, comment215, comment216, comment217, comment218, comment219, comment220, comment221, comment222, comment223, comment224, comment225, comment226, comment227, comment228, comment229, comment230, comment231, comment232, comment233, comment234, comment235, comment236, comment237, comment238, comment239, comment240, comment241, comment242, comment243, comment244, comment245, comment246, comment247, comment248, comment249, comment250, comment251, comment252, comment253, comment254, comment255, comment256, comment257, comment258, comment259, comment260, comment261, comment262, comment263, comment264, comment265, comment266, comment267, comment268,  comment271, comment272, comment273, comment275, comment276, comment277, comment278, comment279, comment280]

    for comment in all_comments:
        comment.song = all_songs[comment.song_id - 1]
        comment.user = all_users[comment.user_id]
        comment.like = sample(all_users, randint(0, len(all_users)))

    db.session.add_all(all_comments)
    db.session.commit()

def undo_comment_seeds():
    db.session.execute(text("DELETE FROM comments"))
    db.session.execute(text("DELETE FROM comment_likes"))
    db.session.commit()






















